spring:
  application:
    name: "config-server"
  config:
    import: "optional:configserver:"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CouncillorTalis/spring-cloud-config.git

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8080/eureka/"
